### ISSUE TITLE
Management tooling - Traffic viewer

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#150]
Subissue of #117 

We want to support recording of all evitaDB traffic for debugging and testing. This includes: executed queries/mutations, fetches and so on. We also want UI for that. There will be listing of all recordings, functionality to start and stop recording, download recording, replay queries and viewing recording detail.

This is basic listing of existing recording with active new recording that has not been stopped yet. Finished recordings can be downloaded replayed or opened.

![Image](https://github.com/lukashornych/evitalab/assets/13931450/06a89467-de5b-455b-b954-27f0e05a25e0)

This is similar listing but for dev mode of evitaDB i.e. when transient memory buffer for recording is present (record everything into rewritable buffer, can previewed but not downloaded).

![Image](https://github.com/lukashornych/evitalab/assets/13931450/2c51fb6e-e10a-4658-b572-af41bd7b1191)

This is a simplified detail of a single recording. Each query has some metadata, queries can be filtered and opened in evitaQL/GraphQL console for individual execution.

![Image](https://github.com/lukashornych/evitalab/assets/13931450/2ee8f20d-abd0-4923-be6e-50967740059a)

In case of GraphQL queries, the execution of each GQL request is a little bit more complex because it is usually constructed of several evitaQL subquries. And we want to aggregate it into a single GraphQL query tree in the UI. The tree would allow opening the root GraphQL request in separate GraphQL console window as well as opening individual subqueries 

![Image](https://github.com/user-attachments/assets/d52b78a2-35be-4871-bd81-17741cf7b589)

For the recording detail, we also want to listen for new traffic using stream from server and display refresh button with number of new records.

In the initial implementation, we will support detail only for queries. The other traffic entities will be just listed for now. We will implement details for other traffic types in the future.

**Comment by lukashornych** [comment]
@novoj First version is ready in the evitaDB build, please try it and test it and report issues back here, thanks. Following are known issues or missing features that I need to figure out yet:
- [ ] cannot start recording again until previous task is cleared by server (i think this problem is present even in JFR recordings)
- [ ] filter form in history listing doesn't support submit, full history refresh must be performed in order to filter to be activated
- [ ] record metadata cannot be copied by clicking
- [ ] `issues creation` error message isn't handled, full history reload must be performed manually
- [ ] record duration metadata item has static threshold for coloring, needs to depend on the record type
- [ ] and some stylistic issues that don't interfere with usability

I've also found possible server issues:
- [ ] when any list of types in capture request is defined only session records seam to be fetched
- [ ] when sending `since` date, it doesn't seam to be filtering anything
- [ ] string label values contain `'` character which is fine for rendering but it is not intuitive for search label values in autocomplete because it must start with the `'` character
- [ ] `TrafficRecorderTask` doesn't have `catalogName` but it is associated with a session (is it possible to add? I need it for stopping the recording)

Also, we need to decide on:
- [ ] threshold for duration coloring for each record type
- [ ] what metadata to display for each record type in final version

**Comment by novoj** [comment]
I think the statistics are not correct (no queries label, yet I can see the query within session).

![Image](https://github.com/user-attachments/assets/19cd0d3c-b08c-444a-a405-50894a35902b)

**Comment by novoj** [comment]
It would be nice, if the date time could be entered / edited manually. Copy & paste from view is impossible.

**Comment by novoj** [comment]
Once date time picker is set it cannot be updated - it sticks to a value that has been entered for the first time.

**Comment by novoj** [comment]
Bytes are not displayed? Maybe too big numbers?

![Image](https://github.com/user-attachments/assets/c754b3ad-02fa-44f2-8ddd-74bd804ef533)

**Comment by novoj** [comment]
I'd rename: 

- `fetched` to `disk accesses` and comment `number of I/O accesses to disk`
- `bytes` to `bytes fetched` and comment `number of Bytes read from disk`

**Comment by novoj** [comment]
Labels (autocompletions) are not reloaded after view has been loaded (it seems).

**Comment by novoj** [comment]
Can't stop traffic recording task:

![Image](https://github.com/user-attachments/assets/35e6df87-9764-4437-bcfd-2fede71146c3)

**Comment by lukashornych** [comment]
@novoj 

> Can't stop traffic recording task:

Please check the list above of possible server issues:

> TrafficRecorderTask doesn't have catalogName but it is associated with a session (is it possible to add? I need it for stopping the recording)

**Comment by novoj** [comment]
> TrafficRecorderTask doesn't have catalogName but it is associated with a session (is it possible to add? I need it for stopping the recording)

Fixed. Pull new version.

**Comment by novoj** [comment]
Can't delete traffic recording file:

```
index-bb1cf041be62ee72.js:39 UnexpectedError: Unexpected error occurred: Missing form reference.
    at f (index-bb1cf041be62ee72.js:1120:133189)
    at eg (index-bb1cf041be62ee72.js:39:1986)
    at al (index-bb1cf041be62ee72.js:39:2057)
    at gbe (index-bb1cf041be62ee72.js:52:32921)
    at I.onConfirm.l.<computed>.l.<computed> (index-bb1cf041be62ee72.js:1035:76981)
    at eg (index-bb1cf041be62ee72.js:39:1986)
    at al (index-bb1cf041be62ee72.js:39:2057)
    at gbe (index-bb1cf041be62ee72.js:52:32921)
    at i (index-bb1cf041be62ee72.js:1035:75359)
    at eg (index-bb1cf041be62ee72.js:39:1986)
```

![Image](https://github.com/user-attachments/assets/c8c35e17-679c-4c52-8a8a-64e54a06888d)

**Comment by novoj** [comment]
Incorrect icon for returned records and also the displayed value:

![Image](https://github.com/user-attachments/assets/f3009652-21bf-4f4c-8be9-50e3a6bb0d7a)

**Comment by novoj** [comment]
gRPC source queries doesn't open evitaQL console, also the errors are not visualized in listing - I propose marking query red + display the error message next to it or in some tooltip over the "error" label.

![Image](https://github.com/user-attachments/assets/4db85745-9239-4224-9ebc-86d360932086)

**Comment by lukashornych** [comment]
@novoj 

> gRPC source queries doesn't open evitaQL console, also the errors are not visualized in listing - I propose marking query red + display the error message next to it or in some tooltip over the "error" label.

Record with error is marked as red, but it doesn't work in the statically built version due to the order of CSS files loading (I haven't figured it out yet) as mentioned earlier. The actual exception message should be visible in a tooltip of a status of each record.

**Comment by novoj** [comment]
The problem with multiple nested source queries for gRPC:

![Image](https://github.com/user-attachments/assets/5454931a-61c0-4ab7-9868-e548a8c99693)

... is probably manifest of mangled order:

![Image](https://github.com/user-attachments/assets/a83923a8-7339-4d08-8a57-60b30cd93b20)

But this is corect the queries probably arrived in parallel into a single session, so that they are written in the order they arrived and progressed through evaluation. You cannot rely on the order of the records in the listing, but you have to pair them by their sourceQueryId.

**Comment by novoj** [comment]
The problem with listing not starting with latest record + 1 when this button is used:

![Image](https://github.com/user-attachments/assets/7985a096-fbbe-4d19-905c-c340fa3e71c8)

... is caused by wrong input to the reversed listing request:

![Image](https://github.com/user-attachments/assets/b40fe19f-59fb-467a-b2f1-99a9a0e8c369)

You must not enter any value for:

```java
@Nullable Long sinceSessionSequenceId,
@Nullable Integer sinceRecordSessionOffset,
```

... but you do provide those. That's why it works this clunky way.

**Comment by lukashornych** [comment]
> The problem with listing not starting with latest record + 1 when this button is used:

🤦 you are right, I'll fix it, thanks.

**Comment by novoj** [comment]
IoFetchCount is displayed incorrectly - source:

![Image](https://github.com/user-attachments/assets/a43c20da-1e3a-4c43-9b37-b2d958ad0217)

Visualization:

![Image](https://github.com/user-attachments/assets/1c22d285-9e9f-4c1e-aed8-57592ec28b64)

**Comment by lukashornych** [comment]
A mechanism to find and fetch missing source query records from the user query has been implemented.

The use case:
1. developer executes GQL query with custom label, e.g. `url = /items`
2. developer opens traffic history and filters the history by label `url = /items`
3. the evitaDB returns only inner evitaDB queries as only they contain the custom labels
4. developer expects to see even the parent source queries to see where the queries came from
5. evitaLab finds all missing source query records for fetched query container
6. evitaLab tries to insert the missing source query records into the history list before visualisation

**Comment by lukashornych** [comment]
@novoj 

It seems okay to me:

<img width="1185" alt="Image" src="https://github.com/user-attachments/assets/13aa88d4-4500-43e9-9374-ea49c9cccc1e" />

In the visualisation code, I take the `X records returned` for the source query record from the source query statistics record. There doesn't seem to be any typo on my end.
